#ifndef AZTHLANGUAGE_STRINGS_H
#define AZTHLANGUAGE_STRINGS_H

#include "AzthLanguage.h" // including LanguageStrings.h will include the system too

enum AzthLangStrEnum {
    AZTH_LANG_REMOVED_ITEMS=0,
    AZTH_LANG_PVP_NPC_SET_ADVICE,
    AZTH_LANG_PVP_NPC_CANNOT_EQUIP,
    AZTH_LANG_RESET_AURAS_ADVICE,
    AZTH_LANG_SHOW_BANK_ITEMS,
    AZTH_LANG_INSTANCE_ONLY,
    // hs
    AZTH_LANG_HS_QUESTS,
    AZTH_LANG_HS_PVP_QUEST,
    AZTH_LANG_HS_DAILY_QUEST,
    AZTH_LANG_HS_WEEKLY_QUEST,
    AZTH_LANG_HS_TW_QUESTS,
    AZTH_LANG_HS_TW_WEEKLY_QUEST,
    AZTH_LANG_HS_TW_DAILY_QUEST,
    AZTH_LANG_HS_TW_DAILY_RANDOM_QUEST,
};

#endif
